apiVersion: v1
entries:
  clickhouse-export:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-01-13T17:44:58.4860911+03:00"
    description: A Helm chart for Kubernetes
    digest: 989579c9000811b4aac7d0f232045b861254a8baf863d53c17d684f160971d5b
    name: clickhouse-export
    type: application
    urls:
    - https://sulaymonhursanov.github.io/clickhouse-exporter/clickhouse-export-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-13T17:44:58.4847499+03:00"
